# Generated by Django 2.1.5 on 2019-02-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20190222_1815'),
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='programs.Version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='resolution_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_bugs', to='programs.Version'),
        ),
    ]
