# Generated by Django 2.1.5 on 2019-02-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190206_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='area',
            table='areas',
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='attachments',
        ),
        migrations.AlterModelTable(
            name='bug',
            table='bugs',
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
        migrations.AlterModelTable(
            name='version',
            table='versions',
        ),
    ]
