# Generated by Django 2.1.5 on 2019-02-22 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190222_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bug',
            name='functional_area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugs.Area'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='resolution_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solved_bugs', to='programs.Version'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='solved_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
