# Generated by Django 2.1.5 on 2019-03-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190314_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='suggested_fix',
            field=models.TextField(blank=True),
        ),
    ]
