# Generated by Django 2.1.5 on 2019-03-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190314_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='programs.Program'),
        ),
    ]
