# Generated by Django 2.1.5 on 2019-02-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190222_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='report_by',
            new_name='reported_by',
        ),
    ]
