# Generated by Django 2.1.5 on 2019-02-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190206_0213'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='version',
            table='program_versions',
        ),
    ]
