# Generated by Django 2.1.5 on 2019-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
